baseURL = "https://mayice.github.io/"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "芸间"
theme = "dream"

copyright = '本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

hasCJKLanguage = true

[params]
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "月阑"
  avatar = "/me/avatar.png"
  motto = "冷处偏佳，别有根芽"

  rss = true

  utterancesRepo = "mayice/comments"
  
  github = "mayice"
  stackoverflow = "14065989/月清寒"

  siteStartYear = 2020

  favicon = "/favicon.ico"

  showSummaryCoverInPost = true

  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true